Home and about pages
lucascomamala/the-portal-capstone pull request #1
Opened 2022-07-27 23:53 UTC by lucascomamala

2022-07-28 02:32 UTC, codecaiine requested changes
Hi @lucascomamala , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

#### Highlights

All linters checks passed :heavy_check_mark:
Descriptive pull request :heavy_check_mark: 
Good project implementation :heavy_check_mark: 
Used Github flow :heavy_check_mark: 

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-07-28 02:32 UTC, codecaiine commented on README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
- [x] Please add to your README  "Acknowledgements" section the appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) who is the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/). :+1:

2022-07-28 02:32 UTC, codecaiine commented on README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
- [x] I would recommend you to record a project presentation video with a maximum length of 5 minutes where you have a clear and objective description of the project the video should also contain a demo of the project, showing the pages on different screen sizes mobile desktop, etc. as required for this project  :smile: 

- [x] Please deploy your project and add the deployed link in the README as required for this project :smiley:

2022-07-28 02:32 UTC, codecaiine commented on index.html
> +    <section id="program">
- [x]  I think for your desktop version of the **main program** card you need to adjust the `opacity`. Please make them similar to the original design as much as possible :

- [x] Please make sure that the button background color is different from the original. You can notice that it just has a text decoration as you see. Please fix it to be the same in the desktop version :smile: 


#### Your design
![Screenshot from 2022-07-28 01-07-28](https://user-images.githubusercontent.com/6615394/181398802-308eb156-b909-485e-a53d-91dd66706dc3.png)

#### Original design
![TTTTd](https://user-images.githubusercontent.com/6615394/181399594-50527205-226e-4f21-bdca-f99ed8c9459f.png)

2022-07-28 02:32 UTC, codecaiine commented on index.html
> +    </section>
- [x] Good job so far with the feature film section :+1:  But I think you should display 6 movies card instead of 2 as defined in the original design. Remember that you need o have a similar design as much as possible. Please fix it  and make sure that you have the same background color for this section :smile: 

### Original design
![Screenshot from 2022-07-28 01-20-01](https://user-images.githubusercontent.com/6615394/181400202-3d0212ba-89a0-4cf1-86f9-8cfb2b867759.png)

### Your design
![Screenshot from 2022-07-28 01-19-08](https://user-images.githubusercontent.com/6615394/181400210-5ad98d06-49cf-4133-9b5b-81ba7ca2aa86.png)

2022-07-28 02:32 UTC, codecaiine commented on index.html
> +    </div>
- [x] Please move the partner section from the `footer` cause Footer represents data related to the author, data that contains copyright information, or some links related to that data. and also please use `section` tag instead of `div` for the partner part in order to be well structured and follow a clear hierarchy, with sections for your HTML markup :smile: 

- [x] Please use the same `background color` and/or the same `opacity ` for your partner's logo as defined in the original design cause your design is a bit different compared to it  :+1: 

#### Your design

![Screenshot from 2022-07-28 01-31-21](https://user-images.githubusercontent.com/6615394/181401080-61696517-7f0d-4247-ba56-860ace8a7fe7.png)

#### Original
![Screenshot from 2022-07-28 01-31-05](https://user-images.githubusercontent.com/6615394/181401084-c1d8ecd3-1737-489f-8a31-f4b678b1fc0f.png)

2022-07-28 02:32 UTC, codecaiine commented on index.html
> +    </div>
- [x] Please use the same `height` `width` and `background color` for your different footer two columns cause it is very different from the original design :+1: 

#### Your design
![Screenshot from 2022-07-28 01-37-49](https://user-images.githubusercontent.com/6615394/181401796-1cf18e08-736b-436a-8734-c90384a9758b.png)

#### Original design
![Screenshot from 2022-07-28 01-39-50](https://user-images.githubusercontent.com/6615394/181401846-449f15a2-ecd4-47eb-b823-995e5df3a103.png)

2022-07-28 02:32 UTC, codecaiine commented on index.html
> +    </section>
- [x] For the desktop version , please fix the text alignment and make it the same as the design and make the different heading and paragraph to be the same width as the original design :+1: 

#### Your design
![Screenshot from 2022-07-28 01-45-13](https://user-images.githubusercontent.com/6615394/181402747-7a4dedb6-7378-4bea-87e0-8852e46fa036.png)

#### Original design
![Screenshot from 2022-07-28 01-44-57](https://user-images.githubusercontent.com/6615394/181402752-a2c4338d-f5c0-4a5b-8e1b-18cbbfb56e94.png)

2022-07-28 02:32 UTC, codecaiine commented on index.html
> +      <ul class="top-nav">
- [x] I would like to recommend you to use `nav` for your navigation because Browsers, such as screen readers for disabled users, can use this element to determine whether to omit the initial rendering of this content. :smile:

2022-07-28 02:32 UTC, codecaiine commented on index.html
> +    <div class="navbar">
- [ ] Good job with your menu but please adjust in order to make it similar to the original design it very important to have the same design :smile: 

#### You design
![Screenshot from 2022-07-28 01-58-12](https://user-images.githubusercontent.com/6615394/181403760-2fa1e5be-3be2-43dc-b167-fe9a6dc6c662.png)

### Orignal design
![Screenshot from 2022-07-28 01-57-38](https://user-images.githubusercontent.com/6615394/181403762-f0d9ffa7-37c9-43b3-97d8-ed922befea9f.png)

2022-07-28 02:32 UTC, codecaiine commented on about.html
> +        <h1>Sundance Film Festival 2023</h1>
- [ ] Please reduce the `font size` of your title `<h1>` cause it looks bigger than the original design :+1: 

#### Original design
![Screenshot from 2022-07-28 02-03-01](https://user-images.githubusercontent.com/6615394/181404306-ad644146-2892-4525-97ae-05c604c2c237.png)

#### Your design
![Screenshot from 2022-07-28 02-02-45](https://user-images.githubusercontent.com/6615394/181404308-d180d7ca-649e-4f10-b333-971c1453d92b.png)

2022-07-28 02:32 UTC, codecaiine commented on about.html
> +        <p class="contact-email">festival2023@sundace.com</p>
- [ ] Please use the same `width` and `height` as defined in the original design :smile:

2022-07-28 02:32 UTC, codecaiine commented on about.html
> +      </div>
- [ ] Please use the same design as defined in the original design. You can clearly see the difference from the original please work on it and make them the same  cause you need to stick the original design as much as possible :smile: 

#### Original 
![Screenshot from 2022-07-28 02-06-52](https://user-images.githubusercontent.com/6615394/181404861-3c6a082f-304c-49bd-bd30-0b28c143ebe4.png)

#### Your design
![Screenshot from 2022-07-28 02-06-41](https://user-images.githubusercontent.com/6615394/181404870-0a6f23f7-ebc7-4d4f-a706-c8064d5ecc74.png)

2022-07-28 02:32 UTC, codecaiine commented on about.html
> +    </section>
- [ ] Please use the same `height `and `width` as defined in the template to make them similar cause you need to stick the original design as much as possible :smile: 

##### Original
![Screenshot from 2022-07-28 02-10-51](https://user-images.githubusercontent.com/6615394/181405306-f7c02422-d33f-4783-a4a1-85d69a880b71.png)

#### Your design
![Screenshot from 2022-07-28 02-10-30](https://user-images.githubusercontent.com/6615394/181405308-2b1db11c-f167-4b4d-8fca-4f8d81f9e3ba.png)

2022-07-28 02:32 UTC, codecaiine commented on index.html
> +<!DOCTYPE html>
- [ ] Please follow the design guidelines and work in the opacity for your program section to make your mobile version similar to the original version :smile:
#### Original design
![DDDDDD](https://user-images.githubusercontent.com/6615394/181406140-64fbacad-4f03-4152-b9ad-c7862fc83de1.png)

### Your design
![Screenshot from 2022-07-28 02-15-17](https://user-images.githubusercontent.com/6615394/181406145-89775512-2890-487b-ac07-d2537fba9801.png)
![Screenshot from 2022-07-28 02-21-39](https://user-images.githubusercontent.com/6615394/181406428-7563a9eb-9f49-4724-a61e-d03ce3f4c0ad.png)

2022-07-28 02:32 UTC, codecaiine commented on index.html
> +<html lang="en">
- [ ] There is a big difference between your design for the featured film section and the original design Please make this section similar to the original design cause you need to stick it as much as possible :+1: 
![Screenshot from 2022-07-28 02-24-52](https://user-images.githubusercontent.com/6615394/181406919-da51bdab-31ff-4341-bd31-ccb0f57d92e2.png)
![Screenshot from 2022-07-28 02-23-04](https://user-images.githubusercontent.com/6615394/181406924-b1bfe4d6-b1aa-4799-9b7b-24f2bf872dac.png)

2022-07-29 04:03 UTC, descholar-ceo requested changes
Hi @lucascomamala , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
👍🏽 You addressed most of the comment given on the first review, but you still need to implement some of them ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-29 04:03 UTC, descholar-ceo commented on README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] This comment is not addressed yet, would work on it ?
  - [ ] The video is missing from the readme file
  - [ ] The deployment link is still missing from the readme file

2022-07-30 01:13 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @lucascomamala, 


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Nice design 🔥 
✅ Professional README file 💯 
✅ Linters are passing 👏 


## Optional suggestions
- The deployment is not showing your page. kindly fix it

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-30 01:14 UTC, merged